#####################################################
# Diagnostics Stack - Used for debugging and troubleshooting
#####################################################
# External Ports
# 3128/tcp     = proxy:HTTP/HTTPS/FTP Proxy Server

version: '3.8'

volumes:
  proxy_volume:

networks:
  overlay_network:
    driver: overlay
    attachable: true

services:
 #####################################################
  # HTTP / HTTPS / FTP Proxy Server
  proxy:
    image: sameersbn/squid
    volumes:
      - proxy_volume:/var/spool/squid
    ports:
      - '3128:3128'
    dns:
      - 192.168.1.2
      - 192.168.1.3
    networks:
      - overlay_network
    deploy:
      replicas: 1

  #####################################################
  # diag-tools
  diag-tools:
    image: docker.pkg.github.com/rodneywimberly/dockerrepositories/diag-tools:1.0
    dns:
      - 192.168.1.2
      - 192.168.1.3
    networks:
      - overlay_network
    deploy:
      replicas: 1
