#!/bin/sh

ESCAPE=\\e

SET_BOLD=1
SET_DIM=2
SET_UNDERLINE=4
SET_BLINK=5
SET_REVERSE=7
SET_HIDDEN=8

RESET_ALL=0
RESET_BOLD=21
RESET_DIM=22
RESET_UNDERLINE=24
RESET_BLINK=25
RESET_REVERSE=27
RESET_HIDDEN=28

FOREGROUND_DEFAULT=39
FOREGROUND_BLACK=30
FOREGROUND_RED=31
FOREGROUND_GREEN=32
FOREGROUND_YELLOW=33
FOREGROUND_BLUE=34
FOREGROUND_MAGENTA=35
FOREGROUND_CYAN=36
FOREGROUND_LIGHT_GRAY=37
FOREGROUND_DARK_GRAY=90
FOREGROUND_LIGHT_RED=91
FOREGROUND_LIGHT_GREEN=92
FOREGROUND_LIGHT_YELLOW=93
FOREGROUND_LIGHT_BLUE=94
FOREGROUND_LIGHT_MAGENTA=95
FOREGROUND_LIGHT_CYAN=96
FOREGROUND_WHITE=97

BACKGROUND_DEFAULT=49
BACKGROUND_BLACK=40
BACKGROUND_RED=41
BACKGROUND_GREEN=42
BACKGROUND_YELLOW=43
BACKGROUND_BLUE=44
BACKGROUND_MAGENTA=45
BACKGROUND_CYAN=46
BACKGROUND_LIGHT_GRAY=47
BACKGROUND_DARK_GRAY=100
BACKGROUND_LIGHT_RED=101
BACKGROUND_LIGHT_GREEN=102
BACKGROUND_LIGHT_YELLOW=103
BACKGROUND_LIGHT_BLUE=104
BACKGROUND_LIGHT_MAGENTA=105
BACKGROUND_LIGHT_CYAN=106
BACKGROUND_WHITE=107

##########################################################
# Normal
export BLACK="${ESCAPE}[${RESET_ALL};${FOREGROUND_BLACK}m"
export RED="${ESCAPE}[${RESET_ALL};${FOREGROUND_RED}m"
export GREEN="${ESCAPE}[${RESET_ALL};${FOREGROUND_GREEN}m"
export YELLOW="${ESCAPE}[${RESET_ALL};${FOREGROUND_YELLOW}m"
export BLUE="${ESCAPE}[${RESET_ALL};${FOREGROUND_BLUE}m"
export PURPLE="${ESCAPE}[${RESET_ALL};${FOREGROUND_MAGENTA}m"
export CYAN="${ESCAPE}[${RESET_ALL};${FOREGROUND_CYAN}m"
export GRAY="${ESCAPE}[${RESET_ALL};${FOREGROUND_LIGHT_GRAY}m"

##########################################################
# Bold
export BOLD_BLACK="${ESCAPE}[${SET_BOLD};${FOREGROUND_BLACK}m"
export BOLD_RED="${ESCAPE}[${SET_BOLD};${FOREGROUND_RED}m"
export BOLD_GREEN="${ESCAPE}[${SET_BOLD};${FOREGROUND_GREEN}m"
export BOLD_YELLOW="${ESCAPE}[${SET_BOLD};${FOREGROUND_YELLOW}m"
export BOLD_BLUE="${ESCAPE}[${SET_BOLD};${FOREGROUND_BLUE}m"
export BOLD_PURPLE="${ESCAPE}[${SET_BOLD};${FOREGROUND_MAGENTA}m"
export BOLD_CYAN="${ESCAPE}[${SET_BOLD};${FOREGROUND_CYAN}m"
export BOLD_GRAY="${ESCAPE}[${SET_BOLD};${FOREGROUND_LIGHT_GRAY}m"

##########################################################
# Dim
export DIM_BLACK="${ESCAPE}[${SET_DIM};${FOREGROUND_BLACK}m"
export DIM_RED="${ESCAPE}[${SET_DIM};${FOREGROUND_RED}m"
export DIM_GREEN="${ESCAPE}[${SET_DIM};${FOREGROUND_GREEN}m"
export DIM_YELLOW="${ESCAPE}[${SET_DIM};${FOREGROUND_YELLOW}m"
export DIM_BLUE="${ESCAPE}[${SET_DIM};${FOREGROUND_BLUE}m"
export DIM_PURPLE="${ESCAPE}[${SET_DIM};${FOREGROUND_MAGENTA}m"
export DIM_CYAN="${ESCAPE}[${SET_DIM};${FOREGROUND_CYAN}m"
export DIM_GRAY="${ESCAPE}[${SET_DIM};${FOREGROUND_LIGHT_GRAY}m"

##########################################################
# No Color
export NO_COLOR="${ESCAPE}[${RESET_ALL}m"

##########################################################
# Logging text colors
export BOLD_GRAY_UNDERLINE="${ESCAPE}[${SET_BOLD};${SET_UNDERLINE};${FOREGROUND_LIGHT_GRAY}m"
export BOLD_GREEN_UNDERLINE="${ESCAPE}[${SET_BOLD};${SET_UNDERLINE};${FOREGROUND_GREEN}m"
export PURPLE_UNDERLINE="${ESCAPE}[${RESET_ALL};${SET_UNDERLINE};${FOREGROUND_MAGENTA}m"
export NO_COLOR_UNDERLINE="${ESCAPE}[${RESET_ALL};${SET_UNDERLINE}m"

set_color() {
  COLOR=$1
  echo -e "${ESCAPE}[${COLOR}m"
}

no_color() {
  echo -e  "${NO_COLOR}"
}

remove_colors() {
  # sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"
  sed "s/\x1B\[\([0-9]\{1,2\}\(;[0-9]\{1,2\}\)\?\)\?[mGK]//g"
}
