###########################################################################################################
# Core Stack
# HA Service discovery, health checks, load-balancing,
# DNS name lookup, routing intentions, KV store,
# DNS Server, Secret Store/Vault, & Reverse Proxy / Portal
###########################################################################################################
version: "3.8"

volumes:
  consul_data:

networks:
  admin_network:
    external: true

services:
  consul:
    image: microserviceframework/consul:dev
    command: agent -join consul.service.consul
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - consul_data:/consul/data
    env_file:
      - ./shared/scripts/core.env
    ports:
      - target: 8500
        published: 8500
        protocol: tcp
        mode: host
    networks:
      admin_network:
        aliases:
          - consul.service.consul
    deploy:
      endpoint_mode: dnsrr
      mode: global

  dns1: &dns-template
    image: microserviceframework/dns:dev
    init: true
    depends_on:
     - consul
    env_file:
      - ./shared/scripts/core.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_ADMIN
    networks:
      admin_network:
        ipv4_address: 192.168.100.2

  dns2:
    <<: *dns-template
    networks:
      admin_network:
        ipv4_address: 192.168.100.3

  registrator:
    image: gliderlabs/registrator:latest
    init: true
    depends_on:
       - consul
       - dns
    command: -cleanup -internal consul://consul.service.consul:8500
    env_file:
      - ./shared/scripts/core.env
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - admin_network
    deploy:
      mode: global
    dns:
      - 192.168.100.2
      - 192.168.100.3

  vault:
    image: microserviceframework/vault:dev
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./shared/scripts/core.env
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    networks:
      - admin_network
    dns:
      - 192.168.100.2
      - 192.168.100.3
    depends_on:
      - consul
      - dns
    deploy:
      mode: global

  portal:
    image: microserviceframework/portal:dev
    init: true
    env_file:
      - ./shared/scripts/core.env
    ports:
      - 5000:80
    networks:
      - admin_network
    dns:
      - 192.168.100.2
      - 192.168.100.3
    depends_on:
      - consul
      - dns
      - vault
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

