#####################################################
# External Ports
# 3128/tcp     = proxy:HTTP/HTTPS/FTP Proxy Server

version: '3'

networks:
  consul_network:
    external: true

services:
 #####################################################
  # HTTP / HTTPS / FTP Proxy Server
  proxy:
    image: sameersbn/squid
    restart: always
    volumes:
      - '/path/to/squid.conf:/etc/squid/squid.conf'
      - '/srv/docker/squid/cache:/var/spool/squid'
    ports:
      - target: 3128
        published: 3128
        protocol: tcp
        mode: host
    networks:
      - consul_network
    dns:
      - 192.168.1.2
      - 192.168.1.3
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  #####################################################
  # diag-tools
  diag-tools:
    image: diag-tools
    restart: always
    networks:
      - consul_network
    dns:
      - 192.168.1.2
      - 192.168.1.3
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

