###########################################################################################################
# Core Stack
# HA Service discovery, health checks, load-balancing, DNS, service mesh routing, KV store, (HashiCorp Consul)
# HA DNS Server (DnsMasq)
# HA Secret Store/Vault (HashiCorp Vault)
# HA Reverse Proxy / Portal (Nginx)
# DevOps Management Web & Agent - Used to manage dev-ops stuff like Docker (Portainer)
# SSH Server - Used to allow dev browser to act as if it is located and routed within the cluster (OpenSSH)
###########################################################################################################
# External Ports
# 14403     = ssh - SSH Server
# 5000      = portal - HTML UI
# 8200      = vault - HTML UI

version: "3.8"

volumes:
  consul_data:
  portainer_data:

networks:
  admin_network:
    external: true

services:
  consul:
    image: microserviceframework/consul:dev
    command: agent -join consul.service.consul
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - consul_data:/consul/data
    env_file:
      - ./scripts/core.env
    ports:
      - 8500:8500
    networks:
      admin_network:
        aliases:
          - consul.service.consul
    deploy:
      # endpoint_mode: dnsrr
      mode: global
      update_config:
        delay: 15s

  dns:
    image: microserviceframework/dns:dev
    init: true
    depends_on:
      - consul
    env_file:
      - ./scripts/core.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_ADMIN
    networks:
      admin_network:
        aliases:
          - dns.service.consul
    deploy:
      replicas: 2

  vault:
    image: microserviceframework/vault:dev
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./scripts/core.env
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    networks:
      - admin_network
    dns:
      - dns.service.consul
    depends_on:
      - consul
      - dns
    # deploy:
    #   mode: global

  portal:
    image: microserviceframework/portal:dev
    init: true
    env_file:
      - ./scripts/core.env
    ports:
      - 5000:80
    networks:
      - admin_network
    dns:
      - dns.service.consul
    depends_on:
      - consul
      - dns
      - vault
      - portainer
      - portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer:
    image: microserviceframework/portainer:dev
    init: true
    env_file:
      - ./scripts/core.env
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - admin_network
    ports:
      - 9000:9000
    dns:
      - dns.service.consul
    depends_on:
      - dns
      - consul
    deploy:
      placement:
        constraints: [node.platform.os == linux]

  portainer-agent:
    image: microserviceframework/portainer-agent:dev
    init: true
    env_file:
      - ./scripts/core.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      # - /:/host
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - admin_network
    dns:
      - dns.service.consul
    depends_on:
      - dns
      - consul
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  ssh-server:
    image: microserviceframework/ssh-server:dev
    init: true
    env_file:
      - ./scripts/core.env
    ports:
      - 14403:22
    networks:
      - admin_network
    dns:
      - dns.service.consul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - dns
      - consul
