#####################################################
# External Ports
# 9000/tcp     = web HTTP UI
# 9001/tcp:udp = agent HTTP REST

version: '3'

services:
  web:
    image: portainer/portainer
    restart: always
    ports:
    - target: 9000
      published: 9000
      protocol: tcp
      mode: host
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/opt/portainer:/data'
    networks:
      - portainer_network
      - consul_network
    deploy:
      mode: replicated
      replicas: 0
      placement:
        constraints: [node.platform.os == linux]

  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_network
      - consul_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  portainer_network:
    external: true

  consul_network:
      external: true
